[package]
name = "simple_game"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.3.0"
anyhow = "1.0.86"
winit = "0.30.5"
vello = "0.2.1"
vello_svg = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parley = "0.1.0"